//Inspired by: https://github.com/jenkinsci/kubernetes-plugin/blob/master/README.md#container-group-support
podTemplate(
    yaml: '''\
      apiVersion: v1
      kind: Pod
      spec:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
        automountServiceAccountToken: false
        containers:
        - name: maven
          image: maven:3.6.2-jdk-8
          args:
          - -f
          - /dev/null
          command:
          - tail
          tty: true
        - name: golang
          image: golang:1.13.3
          command:
          - tail
          args:
          - -f
          - /dev/null
          tty: true
          volumeMounts:
          - name: golang-cache
            mountPath: /.cache
        volumes:
        - name: golang-cache
          emptyDir:
            sizeLimit: 100Mi
    '''.stripIndent(),
) {
    node(POD_LABEL) {
        stage('Get a Maven project') {
            git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            container('maven') {
                stage('Build a Maven project') {
                    sh """
                        mvn -B clean install
                    """
                }
            }
        }

        stage('Get a Golang project') {
            git url: 'https://github.com/golang/example.git'
            container('golang') {
                stage('Build a Go project') {
                    sh """
                    # Prepare it
                    mkdir -p /go/src/github.com/golang
                    ln -s `pwd` /go/src/github.com/golang/example
                    cd /go/src/github.com/golang/example/hello
                    
                    # Build it
                    go build hello.go
                    
                    # Run it
                    ./hello
                    """
                }
            }
        }
    }
}
