//Inspired by: https://github.com/jenkinsci/kubernetes-plugin/blob/master/README.md#container-group-support
podTemplate(
    containers: [
        containerTemplate(
            name: 'maven',
            image: 'maven:3.6.2-jdk-8',
            runAsUser: '1000',
            runAsGroup: '1000',
            ttyEnabled: true,
            command: 'tail',
            args: '-f /dev/null',
        ),
        containerTemplate(
            name: 'golang',
            image: 'golang:1.13.3',
            runAsUser: '1000',
            runAsGroup: '1000',
            ttyEnabled: true,
            command: 'tail',
            args: '-f /dev/null',
        ),
    ],
) {
    node(POD_LABEL) {
        stage('Get a Maven project') {
            git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            container('maven') {
                stage('Build a Maven project') {
                    sh """
                        mvn -B clean install
                    """
                }
            }
        }

        stage('Get a Golang project') {
            git url: 'https://github.com/golang/example.git'
            container('golang') {
                stage('Build a Go project') {
                    sh """
                    # Prepare it
                    mkdir -p /go/src/github.com/golang
                    ln -s `pwd` /go/src/github.com/golang/example
                    cd /go/src/github.com/golang/example/hello
                    
                    # Build it
                    go build hello.go
                    
                    # Run it
                    ./hello
                    """
                }
            }
        }
    }
}
